"""add finished_at to workflow_runs

Revision ID: 017cdcae8aaa
Revises: e31fdcac2c54
Create Date: 2026-06-15 04:59:32.251089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017cdcae8aaa'
down_revision: Union[str, None] = 'e31fdcac2c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'finished_at')
    # ### end Alembic commands ###
