"""Add total_tokens to workflow_runs

Revision ID: ef1d6fc1da97
Revises: d18a63ade839
Create Date: 2026-06-15 03:06:42.103847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef1d6fc1da97'
down_revision: Union[str, None] = 'd18a63ade839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_runs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'total_tokens')
    # ### end Alembic commands ###
